GET http://localhost:11111/clusterdata
Content-Type: application/json

{
  "type": "KMEANS"
}

### Generate Data

GET http://localhost:11111/generatedata
Content-Type: application/json

{"clusterNum": 3, "bounds": [[100, 200],[100, 200],[350, 550],[350, 550],[2000, 2500],[2000, 2500]]}

###